exception TestError();

int function() {
	throw TestError();
	return 10;
}

