// Test output.
import void testPrint(const ubyte * const str, ...);

exception ExampleError(int value);

// Entry point.
export int testEntryPoint(unused int argc, unused ubyte ** argv) {
	try {
		throw ExampleError(1024);
	} catch (ExampleError error) {
		testPrint(C"Caught exception with value %d!", error.value);
	}
	return 0;
}

