// Test output.
import void testPrint(const ubyte * const str, ...);

exception ExampleError(int value);

// Entry point.
export int testEntryPoint(unused int argc, unused ubyte ** argv) {
	try {
		testPrint(C"2: Executing 1.");
		try {
			testPrint(C"1: Executing 0.");
			try {
				testPrint(C"0: Throwing.");
				throw ExampleError(333);
			} catch (ExampleError error) {
				testPrint(C"0: Caught error with value %d.", error.value);
			}
			testPrint(C"1: Successfully finished 0.");
			
			testPrint(C"1: Throwing.");
			throw ExampleError(444);
		} catch (ExampleError error) {
			testPrint(C"1: Caught error with value %d.", error.value);
		}
		testPrint(C"2: Successfully finished 1.");
	} catch (ExampleError error) {
		testPrint(C"2: Caught error with value %d.", error.value);
	}
	return 0;
}

