// Test output.
import void testPrint(const ubyte * const str, ...) noexcept;

exception ExampleError(int value);

void functionThatThrows() {
	testPrint(C"functionThatThrows: Throwing exception.");
	throw ExampleError(8000);
}

void intermediateFunction() {
	functionThatThrows();
}

// Entry point.
export int testEntryPoint(unused int argc, unused ubyte ** argv) {
	try {
		intermediateFunction();
	} catch (ExampleError error) {
		testPrint(C"testEntryPoint: Caught exception with value %d!", error.value);
	}
	return 0;
}

